language: node_js

sudo: false

cache:
  directories:
    - node_modules

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test

notifications:
  slack:
    secure: "StJoLxNQfMA+dFq8lCYQEb4FGloELHZatrfQA5m0fkdIJSPohvXsVV9WLb0pKQewvxjblkZPj9VbPz2/sJeI44lcTm0KcQg1Pf6S/5zMepMpeCnawHOt77aZ5l0o0/2fSo67FVR7zV7esgb3eyBGtd6qAU/EBlNVivJf1ze7awI="
